# Generated by Django 2.2 on 2022-11-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='prod',
        ),
    ]
