# Generated by Django 2.2 on 2022-11-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20221119_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prod',
            new_name='prodt',
        ),
    ]
