# Generated by Django 2.2 on 2022-11-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_img'),
        ('cart', '0004_auto_20221119_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
